#include <bits/stdc++.h>
using namespace std;

void cipher_text(string s) {
    cout << "\n";
    for (int m = 0; m < 26; m++) {
        cout << "M=" << m << ": ";
        for (int i = 0; i < s.length(); i++) {
            int x = s[i] - 'A';
            int y = (x - m + 26) % 26;
            cout << (char) (y + 'A');
        }
        cout << endl;
    }
}

int main() {
    string S;
    cout << "Enter S: "; cin >> S;
    for (int i = 0; i < S.length(); i++) S[i] = toupper(S[i]);
    cipher_text(S);
}

/*
INPUT:
Enter S: VSRQJHEREVTXDUHSDQWU

OUTPUT:
M=0: VSRQJHEREVTXDUHSDQWU
M=1: URQPIGDQDUSWCTGRCPVT
M=2: TQPOHFCPCTRVBSFQBOUS
M=3: SPONGEBOBSQUAREPANTR
M=4: RONMFDANARPTZQDOZMSQ
M=5: QNMLECZMZQOSYPCNYLRP
M=6: PMLKDBYLYPNRXOBMXKQO
M=7: OLKJCAXKXOMQWNALWJPN
M=8: NKJIBZWJWNLPVMZKVIOM
M=9: MJIHAYVIVMKOULYJUHNL
M=10: LIHGZXUHULJNTKXITGMK
M=11: KHGFYWTGTKIMSJWHSFLJ
M=12: JGFEXVSFSJHLRIVGREKI
M=13: IFEDWURERIGKQHUFQDJH
M=14: HEDCVTQDQHFJPGTEPCIG
M=15: GDCBUSPCPGEIOFSDOBHF
M=16: FCBATROBOFDHNERCNAGE
M=17: EBAZSQNANECGMDQBMZFD
M=18: DAZYRPMZMDBFLCPALYEC
M=19: CZYXQOLYLCAEKBOZKXDB
M=20: BYXWPNKXKBZDJANYJWCA
M=21: AXWVOMJWJAYCIZMXIVBZ
M=22: ZWVUNLIVIZXBHYLWHUAY
M=23: YVUTMKHUHYWAGXKVGTZX
M=24: XUTSLJGTGXVZFWJUFSYW
M=25: WTSRKIFSFWUYEVITERXV

-----------------

INPUT:
Enter S: meqefscerhcsyeviekmvp

OUTPUT:
M=0: MEQEFSCERHCSYEVIEKMVP
M=1: LDPDERBDQGBRXDUHDJLUO
M=2: KCOCDQACPFAQWCTGCIKTN
M=3: JBNBCPZBOEZPVBSFBHJSM
M=4: IAMABOYANDYOUAREAGIRL
M=5: HZLZANXZMCXNTZQDZFHQK
M=6: GYKYZMWYLBWMSYPCYEGPJ
M=7: FXJXYLVXKAVLRXOBXDFOI
M=8: EWIWXKUWJZUKQWNAWCENH
M=9: DVHVWJTVIYTJPVMZVBDMG
M=10: CUGUVISUHXSIOULYUACLF
M=11: BTFTUHRTGWRHNTKXTZBKE
M=12: ASESTGQSFVQGMSJWSYAJD
M=13: ZRDRSFPREUPFLRIVRXZIC
M=14: YQCQREOQDTOEKQHUQWYHB
M=15: XPBPQDNPCSNDJPGTPVXGA
M=16: WOAOPCMOBRMCIOFSOUWFZ
M=17: VNZNOBLNAQLBHNERNTVEY
M=18: UMYMNAKMZPKAGMDQMSUDX
M=19: TLXLMZJLYOJZFLCPLRTCW
M=20: SKWKLYIKXNIYEKBOKQSBV
M=21: RJVJKXHJWMHXDJANJPRAU
M=22: QIUIJWGIVLGWCIZMIOQZT
M=23: PHTHIVFHUKFVBHYLHNPYS
M=24: OGSGHUEGTJEUAGXKGMOXR
M=25: NFRFGTDFSIDTZFWJFLNWQ
*/